### ISSUE TITLE
Enhance FitnessFrog To Be A Body Composition Calculator

### ISSUE THREAD

**Issue by sclayturner** [chris-cornish/fitness-frog#2]
Change the code in Program.cs.  Prompt for the values necessary to calculate body composition and inform the user what that body comp "is" and "what it means."  In other words, the app should not simply give the user a body comp (fat/lean tissue/water).  The app should also tell them if the composition is good or bad for their age, etc.  The prompts should only allow acceptable values as inputs (in acceptable ranges), and give the user a second chance to enter a valid input if he/she provides an "invalid" input.

**Comment by sclayturner** [comment]
@chris-cornish ask me questions.  Commit changes frequently.  I will be notified and review.

**Comment by chris-cornish** [comment]
@sclayturner 
Code seems to run and has the appropriate input validation. 
Could definitely use some concatenation, although not really sure how to at this stage.
Program loops for now, but just for testing purposes.
Last 'issue' would be problems using branches and syncing it to GitHub.

**Comment by sclayturner** [comment]
Cool.  We'll look at the branching and synching tomorrow.  I can't pull down and see your updates obviously until we get the synching handled.  I look forward to looking at it with you.

**Comment by chris-cornish** [comment]
Added the code in a text file for now in case you did want to review for now, otherwise I'll see you in the morning.
[bmi.txt](https://github.com/chris-cornish/fitness-frog/files/462819/bmi.txt)

**Comment by sclayturner** [comment]
This was done and verified.
