### ISSUE TITLE
FitnessFrog.Core Domain Entities Require Completion

### ISSUE THREAD

**Issue by sclayturner** [chris-cornish/fitness-frog#5]
@chris-cornish I created on of the domain entities (objects / classes) required for FitnessFrog.  The example is in the FitnessFrog.Core assembly and it is called User.cs.  This is a "public" class in that it can be used by anything that references the FitnessFrog.Core library.  All of its properties are "public" as well so they can be seen and used by any referencing code, including EntityFrameworkCore, which is what we want because EntityFramework is going to load our object from the database and save it back to the database.  The properties that have been defined as class members are all "stubbed" out.  In other words, when it gets compiled, the compiler sees that we have not declared any "private member variables" and so it creates them behind the scenes for us.  This saves time coding.  Otherwise, a traditional class would look something like this:

~~~~
public class User
{
    private int _userId;

    public User()
    {
         Initialize();
    }

    public int UserId
    {
        get
        {
            return _userId;
        }
        set
        {
           _userId = value;
        }
    }

    private Initialize()
    {
        _userId = 0;
    }
}
~~~~

We can accomplish the same thing more quickly by stubbing the properties shorthand (less the initializer):

~~~~
public User
{
    public int UserId { get; set; }
}
~~~~

What I want you to do is think critically about your requirements and the classes you need to define.  I then want you to create the additional classes (objects) for the domain entities.  I will critique and offer guidance after, but take a first stab...

**Comment by chris-cornish** [comment]
Created all the classes I could think of that would be required and committed them on a separate branch (FitnessFrog-v1)

**Comment by sclayturner** [comment]
Not bad! Do me a favor and move all of those classes to the FitnessFrog.Core.Domain assembly.  I don't know why I put the User.cs file in the wrong assembly.  Once you've moved the cs files to the right assembly, commit.  Create a Pull Request.  I'll merge it to the master.

**Comment by sclayturner** [comment]
Merged pull request into master.  I'll pull this down and make any suggestions.

**Comment by sclayturner** [comment]
**Place constructors at the top of the file. See User.cs. Conventional order of class structure is:**

* private variables
* constructor (if any)
* deconstructor (if any)
* public properties
* public methods
* private methods

**Using regions can help you organize a big class.  See User.cs.**

**Having and calling a private Initilize method from your constructors** can be useful because you may ultimately create multiple, overloaded constructors and need to initialize the same members in each.  This reduces code redundancy.  Also, you may need to "re" initialize your class later in another method so why not have it readily available...  See User.cs.

**The name of the file should be consistent with the name of the class**, i.e. DailyLog/Notes.  Pick one. I would pick Notes, BUT... Domain entities will always be singular. Note not Notes.  "Notes" would be a collection property on another class and be of type <Note>.

**On the Food and Exercise classes,** remove the "Note" property and create another collection called "Notes" of type "<Note>."  When the collection loads to Food or Exercise, it will need to know what "type" of Note it is retrieving.  Here we have options.  We could add a "NoteType" and a "NoteTypeId" to the "Note" class.  Later, we configure the collection to load where the NoteType = 'Food' and the NoteTypeId = x where x is the Id of the Food or Exercise as the "type" case may be.  This is the cleanest way.  An alternative would be to create a "FoodId" and a "ExerciseId" on the Note class.  Then, we can maintain context when loading the collection later.  Where this approach gives us the straightforward "primary key" "foreign key" relationship we seek across two diffent applications of a Note, it is not elegant.  Imagine that you want to have another class later, say Trainer, and you want notes provided by the Trainer (Trainer.Notes), you would have to add another TrainerId property to your Note class, and so on.  It would be better to define a "NoteType" on the Note class and an "NoteTypeId."  The "NoteType" provides the context (defines the source of the NoteTypeId).  Again, later we will tell EntityFramework how to load the Notes collection on either Exercise or Food models.

**Fix the Id for the Note class** once you have renamed the Notes class to Note and changed the filename to Note.cs from DailyLog.cs.  The id should be NoteId and be of type int.  Then, you'll want to add a NoteDate property of type DateTime...

Out of curiosity, why have a picture on a Note?  Just wondering.

**Replace the "Name" property on Exercise with "ExerciseType."**  This is something we can select from a list, much like how we set "NoteType" on a Note.  I will explain how we do that when we get to the controllers in the UI...  For a preview, you can look at the new static class EntityHelper.cs.

**I would rename the Workout class and call it "Day."** I would in tandem get rid of the FoodLog. You can consolidate the two concepts...  A "Day" would have a collection of Exercises (like you do now on Workout) AND a collection of Foods.  You may not have any exercises on a given Day, but you can still log Foods.  In other words, a "Day" just becomes a Date/Time stamped collection of the exercises you performed and the foods you ate.

**On Exercise, change Unit to UnitType and make it a string...**

**A "User" must be associated with each object really.**  You need to add UserId to every class.

**You need to document every public member with a summary, or none at all.**  Get in the habit of documenting everything.  Use the xml `<summary></summary>` comments to document public members.  Use the `// or /**/` method for internal notes that coders would read IF they have access to the class.  The xml comments provide the intellisence comments for developers who may be working with a compiled version and not have access to the underlying code.

**Add Creation and ModificationDates** to every class. It's just good practice.  Technically, common members like this could be moved to a base class, but we're not there yet.

**Optimal Model**

* Day
 * DayId
 * EntryDate
 * Exercises (collection)
 * Foods (collection)
 * UserId
 * CreationDate
 * ModificationDate

* Exercise
 * ExerciseId
 * ExerciseType
 * Sets
 * Reps
 * Weight
 * UnitType
 * Notes (collection)
 * UserId
 * CreationDate
 * ModificationDate

* Food
 * FoodId
 * Name
 * Fats
 * Carbs
 * Proteins
 * Calories
 * Notes (collection)
 * UserId
 * CreationDate
 * ModificationDate

* Note
 * NoteId
 * NoteDate
 * Note (string that contains the note)
 * Picture (if you really need it - think about where pics would really apply)
 * NoteType (Food or Exercise)
 * NoteTypeId  (The FoodId or the ExerciseId as the case may be to which the note relates.)
 * UserId
 * CreationDate
 * ModificationDate

**Comment by chris-cornish** [comment]
@sclayturner 
Okay, so I think I was able to re-work the classes to more of the standard seen in the User.cs file. Really enjoyed the convention of separating out the various regions and commenting out everything(rather than pick and choose). Looks much better that way.
As far as the picture property (maybe notes wasn't the best place for it, maybe overview section) I'm re-thinking having it altogether. With all apps I've used in the past, never once have I used that feature. If I would have it anywhere, maybe just as a users picture (which even on GitHub I don't use).
Having finished a couple of the TreeHouse courses on SQLServers, I'm getting a better picture of how the collections and ids are to be used for each class. Makes a lot more sense now to add the userId, creationdate. modificationdate to each.
One a side note I'll be sure to let you know that I've seen and read over what you've put up for me in the future. Really appreciate all you've been doing and the extent to which you've lent yourself to helping!

**Comment by sclayturner** [comment]
@chris-cornish Congrats! You've completed 1 tier of this multi-tier application.  It looks good to me and it compiles.  I will try to have something new for you every morning.  For this project, we will be moving into the FitnessFrog.Core.Domain.Data assembly.  Here, we will tell EntityFrameworkCore how we want it to interface with the database with more control than the "out of the box" sample apps that Microsoft provides.  By the way...  If you haven't figured it out already - and if I haven't told you already - the value of separating out these assemblies instead of code-writing all in one app, i.e. the UI (ASP.NET MVC) application itself, is this:  By compiling the 1st tier of business objects, that assembly could be pulled into lots of applications instead of having to be rewritten for each...  I do this all the time...  I typically have several applications that rely on the same models and  ultimate database interactions.  I'm going to close this issue.  And... Open a new one in the morning.

**Comment by chris-cornish** [comment]
Sounds great! Look forward to it.
